image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.10.1_3.3.3

stages:
  - build
  - test

variables:
  SBT_OPTS: "-Xmx1G"
  JAVA_OPTS: "-Denv=test"

build:
  stage: build
  script:
    - sbt "scalafmtCheckAll; scalafmtSbtCheck; compile"

test:
  stage: test
  script:
    - sbt test
